debug: false
clave: key
broadcast:
    activado: true
    mensajeBroadcast: '&aGracias a {0} por votarnos! El ya ha obtenido su premio, usa &2/voto40&a y obten el tuyo'
mensaje: '&6Gracias por votarnos! Aqui tienes tu premio: '
comandosCustom: 
    activado: true
    comandos:
    - money add {0} 10
premioFisico:
    activado: true
    items:
    - 267,1
    - 261,1
    - 262,64
    - 364,16
    - 306,1
    - 307,1
    - 308,1
    - 309,1
configVer: 2