name: 40ServidoresMC
main: com.cadiducho.cservidoresmc.bukkit.BukkitPlugin
version: 2.5
author: Cadiducho
api-version: 1.13
description: Enlace para servidores de la web 40ServidoresMC!
commands:
    vote40:
        description: Comando principal de 40ServidoresMC
        aliases: [votar40, voto40, mivoto40]
    update40:
        description: Comando para verificar version
        aliases: [actualizar40, upd40]
    reload40:
        description: Comando para recargar el plugin
        aliases: [recargar40, config40]
    stats40:
        description: Estadisticas de tu servidor
        aliases: []
    test40:
        description: Testea el premio que das a tus jugadores