name: 40ServidoresMC
main: com.cadiducho.cservidoresMC.Bukkit
version: 2.0-Beta
author: Cadiducho
description: Enlace para servidores de la web 40ServidoresMC!
commands:
    vote40:
        description: Comando principal de 40ServidoresMC
        aliases: [votar40, voto40, mivoto40]
    update40:
        description: Comando para verificar version
        aliases: [actualizar40, upd40]
    reload40:
        description: Comando para recargar el plugin
        aliases: [recargar40, config40, load40]
